name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-
      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          VUE_APP_INFURA_KEY: ${{ secrets.VUE_APP_INFURA_KEY }}
          VUE_APP_PINATA_JWT: ${{ secrets.VUE_APP_PINATA_JWT }}
          VUE_APP_PINATA_KEY: ${{ secrets.VUE_APP_PINATA_KEY }}
          VUE_APP_PINATA_SECRET: ${{ secrets.VUE_APP_PINATA_SECRET }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dapp.ipci.io
